### PR TITLE
Update pl.po

### PR DESCRIPTION
**Pull request by misterhat**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818326

### CODE REVIEW

**Comment by hikilaka** [comment]
I don't want this change, it will take away from the feel of the game. Please do not accept the PR. Thanks

**Comment by kjensenxz** [comment]
I agree with @hikilaka, this PR will damage the experience while playing edgar and drive away its community.

**Comment by kjensenxz** [comment]
Furthermore, a downstream bug should be filed upstream (i.e. here) and not just with Debian. :^)

**Comment by punjcoder24** [comment]
As a committed Edgar player, I truly feel that its not within the authors best interests to merge this PR without some considerable thought or guidance from the lord. We want to keep the feel of the game intact and proposing major changes like this could affect gameplay and may even drive away loyal community members.

**Comment by riksweeney** [comment]
Done, thanks.

**Pull request merged**
